name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache node modules
        id: bun-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install bun dependencies
        run: bun install --frozen-lockfile

      - name: Run biome lint check
        run: bun --bun lint

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run NX to build and test
        env:
          BASE_URL: /ungrammar-language-features/
        run: bun --bun nx:ci
