name: Release
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache node modules
        id: bun-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install bun dependencies
        run: bun install --frozen-lockfile

      - name: Run Build VSCode and Dependencies
        run: bun build:vscode

      - name: Publish VSCode
        env:
          VSCE_PAT: ${{ secrets.VSCODE_TOKEN }}
        run: bun publish:vscode

      - name: Publish NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: bun publish:npm
